<?php
/**
 * @author Upment DOO
 * @copyright Copyright (c) 2019 Upment (https://upment.com)
 * @package Upment_Richdata
 */

$_helper = $this->helper('richdata');
?>
<script type="application/ld+json">
{
   "@context": "https://schema.org",
   "@type": "Organization",
   "url": "<?php echo $this->getUrl(); ?>",
   "logo": "<?php echo $_helper->getLogoUrl(); ?>",
   "name": "<?php echo $_helper->getOrgName(); ?>",
   "description": "<?php echo $_helper->getDescription(); ?>",
   "foundingDate": "<?php echo $_helper->getFoundingYear(); ?>",
   "address": {
     "@type": "PostalAddress",
     "streetAddress": "<?php echo $_helper->getStreetAddress(); ?>",
     "addressLocality": "<?php echo $_helper->getTown(); ?>",
     "addressRegion": "<?php echo $_helper->getRegion(); ?>",
     "postalCode": "<?php echo $_helper->getPostalCode(); ?>",
     "addressCountry": "<?php echo $_helper->getCountry(); ?>"
   },
   "contactPoint": [{
      "@type": "ContactPoint",
      "telephone": "<?php echo $_helper->getCustomerSupport(); ?>",
      "email": "<?php echo $_helper->getEmailAddress(); ?>",
      "contactType": "customer support"
   }]<?php if ($_helper->haveAdditionalURLs()) { ?>,
   "sameAs": [
<?php
  $medias = $_helper->getAdditionalURLs();
  $i = 0;
  foreach ($medias as $media) {
    $i++;
    if ($i > 1) echo ",\n";
    echo "     \"" . $media . "\"";
  }
?>

   ]<?php } ?>

}
</script>
